#!/bin/bash

# Variables
SOURCE_DIR="/home/ubuntu/data"       #change the source directory where store my data
BACKUP_DIR="/home/ubuntu/backups"   #change the backup directory(destination)
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
BACKUP_NAME="backup_$TIMESTAMP.tar.gz"

# Create backup
tar -czf "$BACKUP_DIR/$BACKUP_NAME" -C "$SOURCE_DIR" .

# Check if backup was successful
if [ $? -eq 0 ]; then
    echo "Backup successful! File created: $BACKUP_DIR/$BACKUP_NAME"
else
    echo "Backup failed!"
fi
