#!/bin/bash

function is_loyal() {
   read -p "jeetha ne piche mud ke kisko dekha: " bandi
   read -p "jettha ka pyaar %" pyaar
   if [[ $bandi == "daya bhabi" ]];
   then
           echo "jettha is loyal"
   elif [[ "$pyaar -ge 100" ]];
   then
           echo "jeetha is loyal"
   else
           echo "jeetha is not loyal"
   fi
}
is_loyal
